#apiVersion: v1alpha1
#kind: Setting
#metadata:
#  # 修改为你自己的设置名称，要与 plugin.yaml 中配置的 settingName 相同
#  name: hello-world-settings
#spec:
#  forms:
#    - group: basic
#      label: 基本设置
#      formSchema:
#        - $formkit: color
#          help: This will be used for your theme.
#          label: color
#          name: color
#          validation: required
