apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # 它是插件的唯一标识名
  # 包含不超过 253 个字符，仅包含小写字母、数字、“-”或“.”，以字母或数字开头，以字母或数字结尾
  name: plugin-hello-world
spec:
  enabled: true
  # 支持的 Halo 版本，SemVer expression, e.g. ">=2.0.0"
  requires: ">=2.0.0"
  # 插件作者名
  author: halo-dev
  # 插件 logo，可以是域名或相对于项目 src/main/resources 目录的相对文件路径
  logo: https://halo.run/logo
  # 插件配置表单名称，参考表单定义，不需要则可删除
  settingName: hello-world-settings
  # 表单定义对应的值标识名, 推荐命名为 "插件名-configmap"，没有配置 settingName 则可删除此项
  configMapName: hello-world-configmap
  # 通常为插件的 Github 仓库链接，或可联系到插件作者或插件官网或帮助中心链接等
  homepage: https://github.com/guqing/halo-plugin-hello-world
  # 插件的显示名称，它通常是以少数几个字来概括插件的用途
  displayName: "插件 Hello world"
  # 插件描述，用一段话来介绍插件的用途
  description: "插件开发的 hello world，用于学习如何开发一个简单的 Halo 插件"
  # 插件使用的软件协议 https://en.wikipedia.org/wiki/Software_license
  license:
    - name: "MIT"
